"""Model

Revision ID: 222791fb8641
Revises: a747f754e8ed
Create Date: 2023-12-16 11:27:41.895733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '222791fb8641'
down_revision = 'a747f754e8ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('donation', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('donation', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
