"""Add Reservation model

Revision ID: 5c410afc54c2
Revises: e4fe1a1cf462
Create Date: 2023-12-14 15:28:52.310452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c410afc54c2'
down_revision = 'e4fe1a1cf462'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
